auto: true
markdown: rdiscount
pygments: true
permalink: /blog/:title

organization: craftofelectronics
repos:

pages_root: http://craftofelectronics.github.com/
github_root: https://github.com/craftofelectronics/



course: Craft of Electronics
course_abbrev: CRAFToE
sections: ["Labs", "Join Us"]

license_url: http://creativecommons.org/licenses/by/3.0/
license_abbrev: CC BY-SA 3.0

twitter: craftoe
tweets: 3